(* ===================================================================
   H-hat Type Definitions Grammar
   ===================================================================
   Depends on: core.ebnf (simple_id, full_id, type_id)
   =================================================================== *)

type_def                    = "type" ( type_struct | type_enum )
type_struct                 = simple_id "{" struct_member+ "}"
struct_member               = simple_id ":" type_id
type_enum                   = simple_id "{" enum_member+ "}"
enum_member                 = simple_id | type_struct
